### ISSUE TITLE
Bundling doesn't work (ioredis)

### ISSUE THREAD

**Issue by BryanCrotaz** [iopipe/iopipe-js#56]
{ ModuleNotFoundError: Module not found: Error: Can't resolve 'ioredis' in '/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/plugins'
    at factory.create (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/neo-async/async.js:2830:7
    at /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
  name: 'BuildError',
  isBuilderError: true,
  isSilent: undefined,
  isCancellation: undefined,
  broccoliPayload:
   { originalError:
      ModuleNotFoundError: Module not found: Error: Can't resolve 'ioredis' in '/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/plugins'
    at factory.create (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/neo-async/async.js:2830:7
    at /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve 'ioredis' in '/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/plugins'
  Parsed request is a module
  using description file: /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/package.json (relative path: ./dist/plugins)
    resolve as module
      /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/plugins/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/IN/sc-pp-backend-repo-master/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/IN/node_modules doesn't exist or is not a directory
      /var/lib/shippable/build/node_modules doesn't exist or is not a directory
      /var/lib/shippable/node_modules doesn't exist or is not a directory
      /var/lib/node_modules doesn't exist or is not a directory
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules
        using description file: /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/package.json (relative path: ./node_modules)
          using description file: /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/package.json (relative path: ./node_modules/ioredis)
            no extension
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis doesn't exist
      looking for modules in /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules
        using description file: /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/package.json (relative path: ./node_modules)
          using description file: /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/package.json (relative path: ./node_modules/ioredis)
            no extension
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis doesn't exist
            .wasm
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis.wasm doesn't exist
            .wasm
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis.wasm doesn't exist
            .mjs
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis.mjs doesn't exist
            .mjs
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis.mjs doesn't exist
            .js
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis.js doesn't exist
            .js
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis.js doesn't exist
            .json
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis.json doesn't exist
            .json
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis.json doesn't exist
            as directory
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/node_modules/ioredis doesn't exist
            as directory
              /var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/ioredis doesn't exist,
     originalMessage:
      'Module not found: Error: Can\'t resolve \'ioredis\' in \'/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@iopipe/trace/dist/plugins\'',
     nodeId: 20,
     nodeLabel: 'WebpackWriter',
     nodeName: 'WebpackWriter',
     nodeAnnotation: undefined,
     instantiationStack:
      '    at WebpackWriter.Plugin (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli-plugin/index.js:7:31)\n    at WebpackWriter.CachingWriter [as constructor] (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli-caching-writer/index.js:18:10)\n    at new WebpackWriter (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli-webpack/index.js:13:16)\n    at webpackLambdas (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@silvercurve/lambda-server-build-utils/dist/builder.js:188:16)\n    at LambdaServerBuilder.buildForDeploy (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@silvercurve/lambda-server-build-utils/dist/builder.js:269:26)\n    at LambdaServerBuilder.build (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/@silvercurve/lambda-server-build-utils/dist/builder.js:300:54)\n    at resolve (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)\n    at new Promise (<anonymous>)\n    at TransformNodeWrapper.build (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)\n    at Promise.resolve.then.then.then (/var/lib/shippable/build/IN/sc-pp-backend-repo-master/gitRepo/node_modules/broccoli/lib/builder.js:116:28)',
     location:
      { file: undefined,
        treeDir: undefined,
        line: undefined,
        column: undefined } } }

**Comment by mrickard** [comment]
Thank you for the report, Bryan! Can you pin the previous release while we work out a solution for you?

**Comment by BryanCrotaz** [comment]
Which release should I use? Tried 1.15.1 and 1.16.

As a workaround I’ve switched. To use lambds layers.

Bryan

On 10 Sep 2019, at 13:52, Maurice Rickard <notifications@github.com> wrote:

Thank you for the report, Bryan! Can you pin the previous release while we
work out a solution for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iopipe/iopipe-js/issues/56?email_source=notifications&email_token=AAPMKCZ644P6H6QGVAQEUEDQI6J7RA5CNFSM4IVEQZZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6K67RY#issuecomment-529919943>,
or mute the thread

**Comment by mrickard** [comment]
What happens if you build iopipe-js-trace from the version in this PR? https://github.com/iopipe/iopipe-js-trace/pull/63

(See this related issue: https://github.com/iopipe/iopipe-js-trace/issues/61)

Alternatively, try pinning to 1.14 and see if that works better for you.  (You're probably not tracing ioredis.)
